name: Trigger auto deployment for azsu-app-weather-001

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/azsu-app-weather-001-AutoDeployTrigger-38c0edf6-faaf-4822-b634-b97a11929309.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: mytestcontainerreg001.azurecr.io
          username: ${{ secrets.AZSUAPPWEATHER001_REGISTRY_USERNAME }}
          password: ${{ secrets.AZSUAPPWEATHER001_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mytestcontainerreg001.azurecr.io/weatherapi01:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZSUAPPWEATHER001_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n azsu-app-weather-001 -g azsu-rg-dev-weather-001 --server mytestcontainerreg001.azurecr.io --username  ${{ secrets.AZSUAPPWEATHER001_REGISTRY_USERNAME }} --password ${{ secrets.AZSUAPPWEATHER001_REGISTRY_PASSWORD }}
            az containerapp update -n azsu-app-weather-001 -g azsu-rg-dev-weather-001 --image mytestcontainerreg001.azurecr.io/weatherapi01:${{ github.sha }}
